openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
paths:
  /contacts:
    get:
      summary: Get all contacts
      description: Get all contacts paginated by 10
      parameters:
        - name: page
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
        "500":
          description: Server error
    post:
      summary: Create a new contact
      description: Create a new contact
      responses:
        "201": 
          description: Created
        "400":
          description: Some Field information is invalid
        "500":
          description: Server error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone_number:
                  type: string
                company:
                  type: string
  /contacts/{id}:
    put:
      summary: Update a contact
      description: Update a contact
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200": 
          description: Updated
        "400": 
          description: Some Field information is invalid
        "500":
          description: Server error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone_number:
                  type: string
                company:
                  type: string
    patch:
      summary: Update a contact
      description: Update a contact
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200": 
          description: Updated
        "400": 
          description: Some Field information is invalid
        "500":
          description: Server error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone_number:
                  type: string
                company:
                  type: string
    delete:
      summary: Update a contact
      description: Update a contact
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200": 
          description: Deleted
        "400": 
          description: Contact does not exist
        "500":
          description: Server error
